version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    working_dir: /app
    command: node server.js
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start